spring.application.name=backend


spring.datasource.url=jdbc:mysql://localhost:3306/meeting_booking_db
spring.datasource.username=root
spring.datasource.password=Abhisek@2757
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


jwt.secret=my-super-secret-key-that-is-at-least-32-characters
